### ISSUE TITLE
Support 1:N connection using array field with IDs

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#102]
It is useful for known to be small amount of child items.

**Comment by RunsFor** [comment]
It would be also useful to be able to use associative array keys as IDs in connection

**Comment by Totktonada** [comment]
@RunsFor Can you please clarify it in a bit more formal way? Some example or kinda.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
