### ISSUE TITLE
Add notes on new usability features to README.md

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#110]
New features should be described. Related to #59 and #60. List of new features:
1. Zero config
2. `require('graphql').execute()/compile()` functionality
3. GraphiQL
4. Config complimentation
Also I propose to re-work the whole README so it can be used by any new user of our lib. Add 'Usage' section and so on.

**Comment by Totktonada** [comment]
@SudoBobo It seems that README now have the information you mentioned. Do you plan to do some more work in the scope of this issue or it can be closed?

**Comment by SudoBobo** [comment]
@Totktonada There is still nothing on config complementation (case when we do `local gql_wrapper = graphql.new({connections = connections})`) I'll add it today and when we could close the ticket.

**Comment by Totktonada** [comment]
@SudoBobo Please, base your branch on PR #168, because I’ll merge it soon.

**Comment by SudoBobo** [comment]
@Totktonada ok

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
