### ISSUE TITLE
Add support for primary index with nesting fields

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#120]
Fields by name `x.y.z` where `x` and `y` are records

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
