### ISSUE TITLE
Remove code duplication in multi-head connections

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#123]

**Comment by Totktonada** [comment]
Seems to be done with PR #168 (1d2d206d23c6459bd96d8807167fd9952e95d7ac): resolve function code now reused. We still have separate function for 'boxing' multi-head connections and regular unions (and they cannot have 'List' postfix, yep?), but I don’t sure it is avoidable.

@SudoBobo Is it can be closed or we want to track something here?

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
