### ISSUE TITLE
Return error code in case of an error

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#134]
It would be great to handle errors from graphql accordingly by using error code. Currently is just asserts and returns error message

**Comment by Totktonada** [comment]
Needed at least the following error codes:

- variables don't fit well with a query

By the way I think that it should be okay to still use error(), but throw an object instead of a string.

**Comment by opomuc** [comment]
Add one to the list:
* query execution timeout exceeded
```
Error catched: query execution timeout exceeded, use timeout_ms to increase it
Error occured at '/usr/share/tarantool/graphql/accessor_general.lua:869'

[C   ] function 'assert' at <[C]:-1>
[Lua ] function 'process_tuple' at </usr/share/tarantool/graphql/accessor_general.lua:869>
[Lua ] function 'select' at </usr/share/tarantool/graphql/accessor_general.lua:1037>
[Lua ] function 'defaultResolver' at </usr/share/tarantool/graphql/tarantool_graphql.lua:539>
[Lua ] function 'fn' at </usr/share/tarantool/graphql/core/execute.lua:110>
[Lua ] function 'fun' at </usr/share/tarantool/graphql/core/util.lua:5>
...

```

**Comment by Totktonada** [comment]
It seems not so important for now, so I moved it from 0.0.1 milestone.

**Comment by opomuc** [comment]
* Incorrect type for service variables (limit, offset, etc)
```
Error catched: args.limit must be a number or nil, got string
Error occured at '/usr/share/tarantool/graphql/accessor_general.lua:971'
[C   ] function 'assert' at <[C]:-1>
[Lua ] function 'select' at </usr/share/tarantool/graphql/accessor_general.lua:971>
[Lua ] function 'defaultResolver' at </usr/share/tarantool/graphql/tarantool_graphql.lua:539>
```

**Comment by opomuc** [comment]
* couldn't create object from tuple??
```
Error catched: count[1] is not equal to objs count[0]
Error occured at '/usr/share/tarantool/graphql/accessor_general.lua:1085'
[C   ] function 'assert' at <[C]:-1>
[Lua ] function 'select' at </usr/share/tarantool/graphql/accessor_general.lua:1085>
[Lua ] function 'defaultResolver' at </usr/share/tarantool/graphql/tarantool_graphql.lua:539>
[Lua ] function 'fn' at </usr/share/tarantool/graphql/core/execute.lua:110>
[Lua ] function 'evaluateSelections' at </usr/share/tarantool/graphql/core/util.lua:5>
```

This also happens when:
* empty variables for query `variables={}` for `query obtain($var1: String, $limit: Int) `

**Comment by Totktonada** [comment]
- variables don't fit well with a query
  - after #160
- query execution timeout exceeded
  - can be added
- Incorrect type for service variables (limit, offset, etc)
  - after #160
- couldn't create object from tuple??
  - it is the internal error; I’m against of setting code to an error that an user should not see at all; it is better to fix code
- empty variables for query…
  - need to investigate if it is arisen when accessor functions are correct
