### ISSUE TITLE
Support for unions' arguments

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#138]
Related to #109. Current implementation does not support arguments on union fields.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
