### ISSUE TITLE
Chunked data transfer from storage nodes

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#14]
Do not transfer entire result set from storage nodes, it can be very big.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
