### ISSUE TITLE
Refactor tarantool/shard reducer to be usable for graphql reduce

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#15]

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
