### ISSUE TITLE
There is no validation of parameter types

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#160]
This query will be successfull:
```
query service_query_with_skip($uid: Long, $ignore: Boolean) {
  services(uid: $uid) {
    uid
    p1
    p2 @skip(if: $ignore)
  }
}

"variables": { "uid": 1, "ignore": "this_is_not_boolean" }
```
Response
```
    "data": {
        "services": [
            {
                "p1": 123,
                "uid": 1
            }
        ]
    },

```

**Comment by Totktonada** [comment]
Note: a variable values type does not checked for a field too (not only for a directive).

**Comment by Totktonada** [comment]
We need the following checks:

- incorrect argument type
- extra argument
- missing non-null argument (if there is one)
- missing non-null variables (#159)

**Comment by Totktonada** [comment]
Set prio1, because it blocks #134.
