### ISSUE TITLE
Push down filter function to storage nodes

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#18]
Add a plan to push down filter function to storage nodes, to avoid excessive data transfer to the execution node.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
