### ISSUE TITLE
Unique index contraint violation at update can lead to an inconsistent state

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#188]
We perform delete, then insert in `accessor_shard.update_tuple`, so the conflict will occur on the insert operation and the delete will not be rolled back.

@opomuc proposed to make insert and then delete.

**Comment by opomuc** [comment]
After brainstorming found only one case, when proposed behavior might not lead to expected result. When updating parts of a **unique** index (including, but not limited to, shard_key) to **themselves (same value)** a user might expect the same behavior as Tarantool's `space:update()` but instead will recieve an error. Cross-shard update in this case also seems concerning

**Comment by Totktonada** [comment]
@opomuc This case can (and must) be avoided using check that we insert an updated tuple into a storage instance that is different from one from which we’ll delete the tuple then. I’ll leave detailed comments for `update_tuple` function and will give the PR to your review.
