### ISSUE TITLE
Support default values for arguments and variables

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#189]
Including proper validation.

**Comment by RunsFor** [comment]
It would be great to have this ticket implemented! 👍

**Comment by RunsFor** [comment]
Right now, if we are using default values, it is ignored.

Consequentially, it may confuse client when constructing a query.

I.e. I would create a query where I get orders optionally, but by default it should not be queried:

```gql
query obtainUser($name: String!, $with_orders: Boolean = false) {
  user_collection(first_name: $name, limit:1) {
    first_name
    order_connection(limit: 1) @include(if: $with_orders) {
      description
    }
  }
}
```

And response:

```json
{
  "data": {
    "user_collection": [
      {
        "first_name": "Ivan",
        "order_connection": [
          {
            "description": "first order of Ivan"
          }
        ]
      }
    ]
  }
}
```

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
