### ISSUE TITLE
Distributed resource planner

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#19]
With many graphql queries, we may overwhelm storage nodes with requests. We need a distributed planner which would allow to utilize many nodes, a kind of problem solved by Apache Mesos and its ecosystem. Each resource should be characterized with a cost vector, based on the cost model https://github.com/tarantool/graphql.0/issues/22

See also: https://asterix.ics.uci.edu/pub/AsterixDBOverview.pdf
https://asterix.ics.uci.edu/pub/ICDE11_conf_full_690.pdf

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
