### ISSUE TITLE
Name clash when 1:1 connection and multi-head 1:1 connection variant have the same name

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#191]
Object (I guess for the variant) and InputObject for filtering by a connection have the same names.

1. We can use bare names only for box objects, but not for the variant type itself, I think (including muti-head connection).
2. We should not use a bare name for an InputObject for filtering by a connection.

**Comment by SudoBobo** [comment]
I guess we may face the same issue in case of 1:N multihead connections.
