### ISSUE TITLE
Maintain cluster-wide statistics about data and its distribution

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#20]
To be able to perform cost-based query analysis, we need to maintain cluster-wide statistics about data distribution: number of records, index fan-out (unique records vs. all records), data set size for column/space.

Where to store this statistics is yet to be investigated (let's look at newsql vendors and see what they do).

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
