### ISSUE TITLE
Cost model

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#22]
Develop a cost model with which each query, can be assigned a cost: estimated, before execution, and factual, after the fact. The cost model should be used by the planner to assess alternative query plans, and by tests to assess the overall quality of the planner.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
