### ISSUE TITLE
Pass user to graphql_storage.init()

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#221]
Pass a username to `graphql_storage.init`, so that the function is able to grant correct privileges.

Note: to grant privileges, the `box.cfg` should be called first.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
