### ISSUE TITLE
vshard: allow use service fields for bucket id calculation

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#224]
Shard function may, in theory, depend on service fields
(fields which are stored only in a tuple, not object).

Allow using a service field for bucket id calculation and sharding.

P.S. The topic needs to be investigated in terms of application and usecases.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
