### ISSUE TITLE
vshard: allow store bucket_id in service fields

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#225]
bucket_id is sometimes used as a transparent field. Adding it to service fields may allow hiding the field from a GQL user.

P.S. it would require some refactoring, as it will become harder to fetch the bucket id from a parent object.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
