### ISSUE TITLE
vshard: support bfs executor + vshard accessor

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#226]
Support bfs executor + vshard accessor.

Possible problems:
1. Vshard router call can reroute a call in case of bucket migration. The executor should deal with this problem on its own.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
