### ISSUE TITLE
Canonical data set

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#23]
Add a canonical data set to the test suite to evaluate the effectiveness of the optimizer based on the cost model https://github.com/tarantool/graphql/issues/22.

Having a canonical data set, and a test set of graphql queries, we can cover the optimizer with functional tests.

**Comment by Totktonada** [comment]
TPC-H mentioned in Hyracks perf. evaluation (see #19 for links).

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
