### ISSUE TITLE
Export execution plan

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#24]
Allow to export execution plan in some plan text format, to be able to cover optimizer decisions with functional tests.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
