### ISSUE TITLE
Graphql Subscriptions

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/graphql.0#240]
The main goal of subscriptions is to show the most actual info on any UI (desktop, mobile, web) for every user.

The general case is consistence between backend state and user UI controls. It's comfortable for user to understand what state is on backend and what actions can be applied for such state. If backend state can be changed and can be used only by single user no subscriptions needed. In any other cases subscriptions is needed.

General case:
Some users inserts data into tarantool and memory limit reached. After this event fired insert action can be disabled to signal that no more data can be sent.

Case of collaboration work:
For example there is user queue to moderate some objects. After some object pop from queue triggered event updates user UI and deletes such object from list.

And I think there is tow kind of subscription channels:
 - predefined built-in which contains some system-wide or others backend events 
 - handmade which can be made by developer

Handmade channels can be made only for data manipulations events. For example, "send event when object with id 123 is changed" or even more specialised "send me event when field Addr of object 123 is changed".

Handmade channels can be defined by InputObject, which in general is AST of DSL which specifies event.

Graphql subscriptions required fullduplex (or pseudo fullduplex http poll) transport. I think it's other issue.

**Comment by Totktonada** [comment]
Origin of the issue and start of the discussion: PR #216.

**Comment by filonenko-mikhail** [comment]
Overengineered
