### ISSUE TITLE
Support query execution timeout

### ISSUE THREAD

**Issue by kostja** [tarantool/graphql.0#25]
Allow to interrupt execution of a complex query when a timeout expires.

**Comment by Totktonada** [comment]
Why we can not just create a fiber and kill it by timeout?

**Comment by Khatskevich** [comment]
The first implementation can be the following:
 - Set `query_timeout` variable to query context at the beginning of an execution.
 - Check `fiber.time64() < query_timeout` on each itaration.

Cons:
 - do not need any monitoring fiber-killers
 - `fiber.time64()` is fast

Disses:
 - `fiber.timeout64()` is updated on yields only and in case of local memex will not change during all query execution.

**Comment by Khatskevich** [comment]
Key points:
1. use `clock.monotonic64()` because it is fast and it changes without yields
2. place the hook to `accessor.new()`, and move to `tgql.compile` after #59
