### ISSUE TITLE
Integrate travis-ci

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#27]

**Comment by SudoBobo** [comment]
It seems worthy to generate and deploy (github pages?) documentation on every push to master. Also the script itself may be simplified and clarified. And we may want to run tests on various platforms, not only on ubuntu trusty.

**Comment by Totktonada** [comment]
We were thinking about deploy docs on tarantool website, but github pages seems to be good idea.

> Also the script itself may be simplified and clarified.

Exactly what?

> And we may want to run tests on various platforms, not only on ubuntu trusty.

We have no platform-specific code, don’t see much sense.
