### ISSUE TITLE
Aliases with the same name pass through compile

### ISSUE THREAD

**Issue by opomuc** [tarantool/graphql.0#277]
```
query aliasTestFail2($individual_id: String) {
  example_alias: individual(individual_id: $individual_id) {
    individual_id
  }
  example_alias: individual(individual_id: $individual_id) {
    last_name
  }
}
```
Above query compiles but when trying to execute fails with error:
```
{
      "message": "two selections into the one field: example_alias"
}
```

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
