### ISSUE TITLE
Accessor should consider avro schema evolution

### ISSUE THREAD

**Issue by Kasen** [tarantool/graphql.0#52]
We have two versions of Avro-schema and four service fields:
0001:
```
"service": {
    "type": "record",
    "name": "service",
    "fields": [
        {"name": "uid", "type": "string"},
        {"name": "p1", "type": "long"},
        {"name": "p2", "type": "long"}
    ]
}
```

0002:
```
"service": {
    "type": "record",
    "name": "service",
    "fields": [
        {"name": "uid", "type": "string"},
        {"name": "p1", "type": "long"},
        {"name": "p2", "type": "long"},
        {"name": "p3", "type": "string", "default": "test avro default"}
    ]
}
```

If data has been pushed in tarantool, then we the tuple `['79031234566', '2451111545', '0002', 1519231048.4021, '79031234566', 2, 2, 'test avro default']` will be stored. So if I try to receive data through graphql, I will receive an error in unflatten function. Because in the first version of the schema we don't have 'p3' field.

**Comment by Totktonada** [comment]
Proposed to handle this on pluggable accessor level with saving accessor-general logic. We need to move unflatten function into as certain accessors’ function, that transforms tuple and metainfo into object. It will allow to implement reading objects using different version of schemas.
