### ISSUE TITLE
build_lookup_index_name collisions are possible

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#68]
build_lookup_index_name hashes indexes that way:
```
            for _, field in ipairs(fields_list) do                              
                name_list[#name_list + 1] = field                               
            end                                                                 
                                                                                
            table.sort(name_list)                                               
            local name_list_str = table.concat(name_list, ',')  
```
Which may produce the same `name_list_str` in the following cases:
1. same key parts in different order
2. field names with , (which is allowed in tarantool)

My suggestion is to delete this cache at all and to optimize prefix_tree_cache.
I suppose that we can cache index lookup results for the query and lookup index once per connection (not per each object) in the query.

**Comment by Totktonada** [comment]
1. Arguments list / finter have no order. Why we should prefer one over another? Based on what?
2. Is there separator fit out needs?

I consider removing too, but don’t want to do so before we’ll have some microbenchmarks. Caching is good idea, we need to consider it too.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
