### ISSUE TITLE
Make connection names unique?

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#70]
# Suggestion
1. make connection names unique per the whole schema
2. change connection description format array[id]=value -> dict[name]=value
## Motivation for (1)
1. In case we create types for connections (for example for nested arguments) GQL requires them to have unique names
2. Our `accessor_general.build_connection_indexes` relies on that. Here is a snippet from the function which may override index in case of connections from different collections to the collection have the same names.
```
            connection_indexes[c.destination_collection][c.name] = {            
                index_name = index_name,                                        
                connection_type = c.type,                                       
            }
```
## Motivation for (2)
1. I suppose the format is easier to parse (for some features I have to do convert to that format by my own)
2. more native for schema description and looks closer to description of other elevents such as collections, schemas and indexes

**Comment by Totktonada** [comment]
It should be noted that (2) is proposal to change *external* API. But it does not lack of sense, though.

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
