### ISSUE TITLE
Add query meta

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/graphql.0#71]
For testing and debugging purposes, we need more information about a query execution
I suggest at least add:
1. Used indexes/warnings that indexes were not used
2. Exec time
3. Number of retrived objects
4. Number of returned objects
5. Number of lookups

Until we do not have strict vision of how it should look like, I suggest add this information in any free form (at least text description, or raw data (index structures themselve)).

**Comment by Totktonada** [comment]
We can collect it in qcontext and then create API for accessor_general <-> tarantool_graphql to pass meta and then return it in tarantool_graphql.

**Comment by Totktonada** [comment]
Meta was added, but some information still doesn't provided:

1. Used indexes/warnings that indexes were not used
2. Exec time

**Comment by Totktonada** [comment]
I'm going to archive the repository. I'll proceed as follows:

* Mark all open pull requests with the `archived` label and close.
* Mark all open issues with `archived` and `wontfix` labels and close.
* Archive the repository.

Consider the following projects:

* https://github.com/tarantool/graphql
* https://github.com/tarantool/graphqlapi
* https://github.com/tarantool/graphqlide
