### ISSUE TITLE
Generate avro-schema for a query with directives

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#85]
The proposal is to extend solution from #7, so it could handle directives (http://facebook.github.io/graphql/October2016/#sec-Type-System.Directives) in GraphQL queries.

**Comment by SudoBobo** [comment]
I think we should just ignore `include` and `skip` directives and generate avro-schema like `include` condition is always `true` and `skip` condition is always `false`. Like this, "turn"  first schema below into second and then use our common query->schema routine.
```
query user_by_order($first_name: String, $description: String,
        $include: Boolean) {
    order_collection(description: $description) {
        order_id
        description
        user_connection @include(if: $include,
                first_name: $first_name) {
            user_id
            last_name
            first_name
        }
    }
}
```
second:
```
query user_by_order($first_name: String, $description: String,
        $include: Boolean) {
    order_collection(description: $description) {
        order_id
        description
        user_connection (first_name: $first_name) {
            user_id
            last_name
            first_name
        }
    }
}
```
The reason for that is that `include` and `skip` directives are about data representation, not about data schema. Query directives are mainly the tool to make flexible queries and reduce overall number of written queries. 
There are also should not be confusion with `non-null` property. `include` condition may be `true` but if the field is nullable we still can retrieve nothing. And again they are describing different things - representation and schema.

**Comment by opomuc** [comment]
@SudoBobo well, 
> directives are about data representation, not about data schema

that is correct. BUT: avro-schema is generated for the **response** of the query, thus must take directives into account. I can propose generate `record*` field in case of both skip and include, meaning the field may or may not be present in the response

**Comment by SudoBobo** [comment]
Discussed with @Totktonada in chat , came to the same conclusion.

**Comment by Totktonada** [comment]
It can be any nulllable type, not only record*. Any field can have a directive.
