### ISSUE TITLE
Add support of fragments' arguments

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/graphql.0#89]
Currently they are not supported by graphql-lua. This will NOT work:
```
... on Image (size: small) {
    resolution
    uploadedAt
}
```
It reduces feature capacity of union connections in compare with 'single' ones, as fragments are the only way to access union fields. See https://github.com/facebook/graphql/issues/204

**Comment by Totktonada** [comment]
I think we can add arguments to 'box field' in order to support arguments for multi-head connections.

**Comment by Totktonada** [comment]
I'll close it as dupe of more general #185.
