### ISSUE TITLE
Filter over boundaries of 1:N connections

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#94]
Consider empty list for a subrequest as a non-match situation.

**Comment by opomuc** [comment]
Basically customer wants such thing:

Let's assume we have a filter `individuals(individual_customer_relation: {uid: $num}, last_name: $last_name)` where `individual_customer_relation` is a 1:N connection to another space. Three situations are possible:
* `last_name` is specified
* `num` is specified
*  both `last_name` and `num` are specified

We need to be able to filter resulting data in all of those 3 situations. When `num` is present -- only those individuals that have >= 1 of connected objects with `uid == num` must be returned. And so on
